version: '3'

services:
  database:
    image: 'postgres:latest'
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - ./.db/:/home/sm2k4/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: sm2k4
      POSTGRES_PASSWORD: heaven123HE!!
      POSTGRES_DB: httpcoffee
    expose:
      - "5432"
