version: '3'

services:
  database:
    image: 'postgres:latest'
    ports:
      - 5432:5432
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${USERNAME}
      POSTGRES_PASSWORD: ${PASSWORD}
      POSTGRES_DB: ${DB}
    expose:
      - "5432"